theme = "ananke"
baseURL = "http://chiple.github.io/"
languageCode = "ja-jp"
title = "test on hugo"
cononifurls = true
publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"
